### ISSUE TITLE
Help for first installation

### ISSUE THREAD

**Issue by cmbant** [carronj/LensIt#2]
Master seems unusable (no setup.py, py2) - add some instruction to use lensitdev or probably better move that to master and arxiv branch the old code?

The readthedocs also makes no mention of branches and install instructions don't work in master.: https://lensit.readthedocs.io/en/latest/ 

I also had to do an unobvious "sudo apt install fftw3-dev" before pip install on the lensitdev branch would work (via pyfftw dependency, which seem to require fftw installed first before pip).

demo_basics.ipynb uses undefined "pl".

**Comment by carronj** [comment]
Thanks Antony for all this. I have made various updates to the master branch (now same as lensitdev), and hopefully adressed your points.
