### ISSUE TITLE
int32

### ISSUE THREAD

**Issue by cmbant** [carronj/LensIt#7]
Turns out that on some systems np.int_ (and possibly int more generally) gives a 32 bit integer, even on 64 bit python (e.g. Anaconda on Windows 64). My student spent some time with weird errors before we finally tracked this down, e.g. this gives int overflow at

https://github.com/carronj/LensIt/blob/844e31ef5a1dff0585fafcb3af37596aefe78b28/lensit/misc/misc_utils.py#L42

and hence negative pp spectrum.at high L. 

Probably safest just to add an assert that int is actually int64, otherwise need to explicitly asarray(dtype=int64..), or check all integer powers.

**Comment by carronj** [comment]
Thanks. This should be fixed now
